<template>
  <select class="textLanguage" :value="modelValue" @input="$emit('update:modelValue', $event.target.value)">
        <option value="" selected disabled hidden>Язык</option>
        <option value="ru">Русский</option>
        <option value="en">Английский</option>
        <option value="fr">Французский </option>
        <option value="sq">Албанский</option>
        <option value="am">Амхарский</option>
        <option value="ar">Арабский</option>
        <option value="hy">Армянский</option>
        <option value="as">Ассамский</option>
        <option value="ay">Аймара</option>
        <option value="az">Азербайджанский</option>
        <option value="bm">Бамбара</option>
        <option value="eu">Баскский</option>
        <option value="be">Белорусский</option>
        <option value="bn">Бенгальский</option>
        <option value="bho">Бходжпури</option>
        <option value="bs">Боснийский</option>
        <option value="bg">Болгарский</option>
        <option value="ca">Каталанский</option>
        <option value="ceb">Себуанский</option>
        <option value="zh-CN">Китайский (упрощенный)</option>
        <option value="zh-TW">Китайский (традиционный)</option>
        <option value="co">Корсиканский</option>
        <option value="hr">Хорватский</option>
        <option value="cs">Чешский</option>
        <option value="da">Датский</option>
        <option value="dv">Дивехи</option>
        <option value="doi">Донгри</option>
        <option value="nl">Голландский</option>
        <option value="en">Английский</option>
        <option value="eo">Эсперанто</option>
        <option value="et">Эстонский</option>
        <option value="ee">Эве</option>
        <option value="tl">Филиппинский</option>
        <option value="fi">Финский</option>
        <option value="fr">Французский</option>
        <option value="fy">Фризский</option>
        <option value="gl">Галисийский</option>
        <option value="ka">Грузинский</option>
        <option value="de">Немецкий</option>
        <option value="el">Греческий</option>
        <option value="gn">Гуарани</option>
        <option value="gu">Гуджарати</option>
        <option value="ht">Гаитянский креольский</option>
        <option value="ha">Хауса</option>
        <option value="haw">Гавайский</option>
        <option value="iw">Иврит</option>
        <option value="hi">Хинди</option>
        <option value="hmn">Хмонг</option>
        <option value="hu">Венгерский</option>
        <option value="is">Исландский</option>
        <option value="ig">Игбо</option>
        <option value="ilo">Илокано</option>
        <option value="id">Индонезийский</option>
        <option value="ga">Ирландский</option>
        <option value="it">Итальянский</option>
        <option value="ja">Японский</option>
        <option value="jw">Яванский</option>
        <option value="kn">Каннада</option>
        <option value="kk">Казахский</option>
        <option value="km">Кхмерский</option>
        <option value="rw">Киньяруанда</option>
        <option value="gom">Конкани</option>
        <option value="ko">Корейский</option>
        <option value="kri">Крио</option>
        <option value="ku">Курдский</option>
        <option value="ckb">Курдский (сорани)</option>
        <option value="ky">Киргизский</option>
        <option value="lo">Лаосский</option>
        <option value="la">Латынь</option>
        <option value="lv">Латышский</option>
        <option value="ln">Лингала</option>
        <option value="lt">Литовский</option>
        <option value="lb">Люксембургский</option>
        <option value="mk">Македонский</option>
        <option value="mai">Майтхили</option>
        <option value="mg">Малагасийский</option>
        <option value="ms">Малайский</option>
        <option value="ml">Малаялам</option>
        <option value="mt">Мальтийский</option>
        <option value="mi">Маори</option>
        <option value="mr">Маратхи</option>
        <option value="mni">Манипури</option>
        <option value="lus">Мизо</option>
        <option value="mn">Монгольский</option>
        <option value="my">Мьянманский</option>
        <option value="ne">Непальский</option>
        <option value="no">Норвежский</option>
        <option value="or">Ория</option>
        <option value="om">Оромо</option>
        <option value="ps">Пушту</option>
        <option value="fa">Персидский</option>
        <option value="pl">Польский</option>
        <option value="pt">Португальский</option>
        <option value="pa">Пенджабский</option>
        <option value="qu">Кечуа</option>
        <option value="ro">Румынский</option>
        <option value="ru">Русский</option>
        <option value="sm">Самоанский</option>
        <option value="sa">Санскрит</option>
        <option value="gd">Шотландский гэльский</option>
        <option value="sr">Сербский</option>
        <option value="st">Сесото</option>
        <option value="sn">Шона</option>
        <option value="sd">Синдхи</option>
        <option value="si">Сингальский</option>
        <option value="sk">Словацкий</option>
        <option value="sl">Словенский</option>
        <option value="so">Сомалийский</option>
        <option value="es">Испанский</option>
        <option value="su">Сунданский</option>
        <option value="sw">Суахили</option>
        <option value="sv">Шведский</option>
        <option value="tg">Таджикский</option>
        <option value="ta">Тамильский</option>
        <option value="tt">Татарский</option>
        <option value="te">Телугу</option>
        <option value="th">Тайский</option>
        <option value="ti">Тигринья</option>
        <option value="ts">Тсонга</option>
        <option value="tr">Турецкий</option>
        <option value="tk">Туркменский</option>
        <option value="ak">Тви</option>
        <option value="uk">Украинский</option>
        <option value="ur">Урду</option>
        <option value="ug">Уйгурский</option>
        <option value="uz">Узбекский</option>
        <option value="vi">Вьетнамский</option>
        <option value="cy">Валлийский</option>
        <option value="xh">Коса</option>
        <option value="yi">Идиш</option>
        <option value="yo">Йоруба</option>
        <option value="zu">Зулу</option>       
    </select>
</template>

<script>
export default {
    props: ['modelValue']
}
</script>